---
- name: Configure pacman
  template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf

- name: Update pacman cache
  pacman:
    update_cache: yes
  tags: always

- name: Install Arch Build System
  pacman:
    name: abs
    state: latest

- name: Install development utilities
  pacman:
    name: "{{ item }}"
    state: latest
  with_items: "{{ common_base_devel_pkgs }}"

- name: Change owner of /var/abs/local
  file:
    path: /var/abs/local
    state: directory
    mode: 0755
    owner: "{{ common_user }}"

- name: Checkout aura-bin
  git:
    repo: https://aur.archlinux.org/aura-bin.git
    dest: /var/abs/local/aura-bin
    accept_hostkey: yes
  become_user: "{{ common_user }}"
  register: __aura_checkout

- block:
  - name: Determine aura-bin package version
    shell: "(grep -oP '(?<=^pkgver=).*' PKGBUILD; printf -- -; grep -oP '(?<=^pkgrel=).*' PKGBUILD) | tr -d $'\n'"
    args:
      chdir: /var/abs/local/aura-bin
    register: __aura_bin_version
    ignore_errors: True
    changed_when: False

  - name: Build aura-bin
    shell: makepkg -s
    args:
      chdir: /var/abs/local/aura-bin
      creates: "aura-bin-{{ __aura_bin_version.stdout }}-x86_64.pkg.tar.xz"
    become_user: "{{ common_user }}"

  - name: Install aura-bin
    pacman:
      name: "/var/abs/local/aura-bin/aura-bin-{{ __aura_bin_version.stdout }}-x86_64.pkg.tar.xz"
      state: present

  when: __aura_checkout.changed

# vim:ft=ansible
