---
- name: Install sysstat
  pacman: name=sysstat state=latest

- name: Create sysstat storage directory
  file:
    path: "{{ common_sysstat_directory }}"
    state: directory
    mode: 0755

- name: Symlink /var/log/sa to sysstat directory
  file:
    src: "{{ common_sysstat_directory }}"
    path: /var/log/sa
    state: link
    force: yes
  when: "common_sysstat_directory != '/var/log/sa'"

- name: Copy sysstat configuration
  template:
    src: sysstat.j2
    dest: /etc/conf.d/sysstat
    mode: 0644

- name: Enable and start sysstat service
  service:
    name: sysstat
    state: started
    enabled: yes

# vim:ft=ansible
