---
- name: Install shell packages
  pacman: name={{ item }} state=latest
  with_items:
    - keychain
    - screen
    - wget
    - mtr
    - traceroute
    - dnsutils
    - pkgfile
    - "net-tools"
    - unzip
    - pwgen
    - moreutils
    - nmap
    - whois

- name: Ensure profile.d exists
  file:
    path: /etc/profile.d
    state: directory
    mode: 0755

- name: Install bash environment scripts into profile.d
  copy:
    src: "{{ item }}"
    dest: "/etc/profile.d/{{ item }}"
    mode: 0755
  with_items:
    - history.sh
    - aliases.sh
    - fixterm.sh

- name: Install packf and unpackf
  copy:
    src: "{{ item }}"
    dest: "/usr/bin/{{ item }}"
    mode: 0755
  with_items:
    - packf
    - unpackf

- name: Configure user's bash runtime
  template: src=bashrc.j2 dest="~{{ common_user }}/.bashrc"
  sudo_user: "{{ common_user }}"

- name: Configure user's bash aliases
  template: src=bash_aliases.j2 dest="~{{ common_user }}/.bash_aliases"
  sudo_user: "{{ common_user }}"

- name: Ensure user's bin directory exists
  file:
    path: "~{{ common_user }}/bin"
    state: directory
    mode: 0755
  sudo_user: "{{ common_user }}"

# vim:ft=ansible
