---
- name: Install development packages
  pacman: name={{ item }} state=latest
  with_items:
    - git
    - python
    - python-virtualenvwrapper
    - python-pip
    - python2-pip

- name: Checkout rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: "~{{ common_user }}/.rbenv"
    depth: 1
  sudo_user: "{{ common_user }}"

- name: Checkout ruby-build for rbenv
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: "~{{ common_user }}/.rbenv/plugins/ruby-build"
    depth: 1
  sudo_user: "{{ common_user }}"

- name: Checkout rbenv-gem-rehash
  git:
    repo: https://github.com/sstephenson/rbenv-gem-rehash.git
    dest: "~{{ common_user }}/.rbenv/plugins/rbenv-gem-rehash"
    depth: 1
  sudo_user: "{{ common_user }}"

# vim:ft=ansible
