---
- name: Install development packages
  pacman: name={{ item }} state=latest
  with_items:
    - git
    - python
    - python-virtualenvwrapper
    - python-pip
    - python2-pip
    - rustup

- name: Checkout rbenv and plugins
  git:
    repo: "{{ item.repo }}"
    dest: "~{{ common_user }}/.rbenv"
    depth: 1
  with_items:
    - { repo: "https://github.com/sstephenson/rbenv.git", ".rbenv" }
    - { repo: "https://github.com/sstephenson/ruby-build.git", ".rbenv/plugins/ruby-build" }
    - { repo: "https://github.com/sstephenson/rbenv-gem-rehash.git", ".rbenv/plugins/rbenv-gem-rehash" }
  sudo_user: "{{ common_user }}"
  tags:
    - ruby
    - rbenv

# vim:ft=ansible
