---
- name: Update pacman cache
  pacman: update_cache=yes
  tags: always

- include: configure_locale.yml
- include: configure_package_management.yml tags=pkg
- include: configure_ntp.yml tags=ntp
- include: configure_sysstat.yml tags=sysstat
- include: configure_environment.yml tags=env
- include: configure_vim.yml tags=vim,dev,env
- include: configure_development_environment.yml tags=dev,env
- include: add_sshkey.yml tags=ssh
